### ISSUE TITLE
Certain subjects not showing up in search.

### ISSUE THREAD

**Issue by gatlee** [ruarai/UnimelbTimetablingApp#3]
Eg https://handbook.unimelb.edu.au/2018/subjects/comp20007/eligibility-and-requirements Does not show up when searching via subject code or name

**Comment by ruarai** [comment]
Everything is currently set up for semester two, so since design of algorithms is only semester one it isn't in the list of subjects.

**Comment by ruarai** [comment]
I do need to make this more clear though, you're definitely not the only one that's tripped up on this
